// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SepandPayMMSApis.Models;

public partial class MMSPortalV3Context : DbContext
{
    public MMSPortalV3Context(DbContextOptions<MMSPortalV3Context> options)
        : base(options)
    {
    }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.Property(e => e.ExpiryDate).HasColumnType("smalldatetime");
            entity.Property(e => e.TokenHash)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.TokenSalt)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.TS).HasColumnType("smalldatetime").HasColumnName("TS");
            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens).HasForeignKey(d => d.UserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_RefreshToken_User");
            entity.ToTable("RefreshToken");
        });


        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.Email).IsRequired().HasMaxLength(50);
            entity.Property(e => e.FirstName).IsRequired().HasMaxLength(255);
            entity.Property(e => e.LastName).IsRequired().HasMaxLength(255);
            entity.Property(e => e.Password).IsRequired().HasMaxLength(255);
            entity.Property(e => e.PasswordSalt).IsRequired().HasMaxLength(255);
            entity.Property(e => e.TS).HasColumnType("smalldatetime").HasColumnName("TS");
            entity.ToTable("User");
        });



        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}